# Podfile
platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_installation
  flutter_application_path = File.expand_path('..')
  load File.join(flutter_application_path, '.flutter-plugins')
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_installation

  pod 'Firebase/Core'
end
